server:
  servlet:
    context-path: /api

spring:
  application:
    name: HMovie
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:HMovie}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:vothanhhuy710}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  cache:
    type: redis

  # 3. Cấu hình Keycloak (Xác minh Token)
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URL:http://localhost:8180}/realms/HMovie
idp:
    url: ${KEYCLOAK_URL:http://localhost:8180}
    client-id: HMovie
    client-secret: ri8WRorWmGFtLyH6GOJAfO8ZR2gE8JZU
